bind_host: 127.0.0.1
bind_port: 8000
graphql_endpoint: https://foo:bar@example.com/graphql
public_url: https://example.com/ow-telegram-notifier/
# ^^^ public_url + "telegram-webhook" will be set up as a webhook callback URL for Telegram
telegram_api_token: '1027654321:ABCDEZ_JnGasdfghjkl8'
telegram_chat_id: '-123456789'
ignore_messages:
- "skip messages with this string in their text"
- "this can also be (regex|regular expression)"
